### PR TITLE
[1307]: Sending emails to multiple email addresses gives error message

### LINKED ISSUE #1307: Sending emails to multiple email addresses gives error message
### Title

Sending emails to multiple email addresses gives error message

### Expected Behavior

Sending emails to multiple email addresses gives error message

### Current Behavior

Sending emails to multiple email addresses gives error message

### Steps to Reproduce

1. Go to Invoice
2. Click menu top right corner to email invoice
3. In "cc", "bcc" or "to" enter multiple email addresses, separated by a comma ","
4. Error message: `the field "cc_mail" must contain a valid email address`

### Possible Solution (Optional)

In mailer_helper.php de email addresses are run through "filter_var" even though they can contain multiple email addresse separated by a comma

### Context (Environment)

Comes from the Forum: https://community.invoiceplane.com/t/topic/11845

### PR DESCRIPTION
**Pull request by nielsdrost7**
using filter_var in mailer_helper caused issues when multiple email addresses were allowed refs https://github.com/InvoicePlane/InvoicePlane/issues/1307

### CODE REVIEW

**Comment by nielsdrost7** [comment]
I'd rather explode on "," and then run each email address through filter_var
But maybe that's for a future version

**Comment by naui95** [comment]
> I'd rather explode on "," and then run each email address through filter_var But maybe that's for a future version

I find it to be a good idea. I would implement it already in `1.6.4` since it's to be considered as a fix to the behavior introduced with `1.6.3` that broke previous functionality.

**Comment by naui95** [comment]
fixes #1307

**Review by naui95 — APPROVED** [review]

**Review by naui95 — APPROVED** [review]

File: application/helpers/mailer_helper.php [hunk 1]
```diff
@@ -211,6 +210,28 @@ function email_quote_status(string $quote_id, $status)
...
+ * Validate email address syntax
+ * $email string can be a single email or a list of emails.
+ * The emails list must be comma separated.
+ *
+ * @param string $email
+ * @return boolean returs true if all emails are valid otherwise false.
+ */
+function validate_email_address(string $email) : bool {
+    $emails[] = $email;
+    if(strpos($email,',') !== false) {
```
Comment (laodc) [inline application/helpers/mailer_helper.php:223]: It might be best to mimic same functionality as phpmail_send:

```php
 $emails = (mb_strpos($email, ',')) ? explode(',', $email) : explode(';', $email);
```

This will in all cases generate an array of addresses that can be traversed through, and allows both , and ; style splittings.

Comment (nielsdrost7) [reply application/helpers/mailer_helper.php:223]: @laodc thanks for your remark, man.
Can you make a PR? This PR has already been merged.

Comment (laodc) [reply application/helpers/mailer_helper.php:223]: Done. #1375

> @laodc thanks for your remark, man. Can you make a PR? This PR has already been merged.
